export enum MetodoPago {
  MASTERCARD_DEBITO = 'MASTERCARD_DEBITO',
  MASTERCARD_CREDITO = 'MASTERCARD_CREDITO',
  PAYPAL = 'PAYPAL',
  TRANSFERENCIA_BANCARIA = 'TRANSFERENCIA_BANCARIA',
  TARJETA = 'TARJETA'
}
